version: 1
#disable_existing_loggers: true

file_handler_log_paths:
    # all file names in any file handlers below will be joined with this common path name
    local: log
    server: /var/log/aoms/

formatters:
    standard:
        format: '%(asctime)s %(name)16s %(levelname)-8s %(message)s'
        datefmt: '%Y-%m-%d:%H:%M:%S%z'
    error:
        format: '%(asctime)s %(name)16s:%(lineno)d %(levelname)-8s %(message)s'
        datefmt: '%Y-%m-%d:%H:%M:%S%z'
    detail:
        format: "%(asctime)s %(levelname)s <PID %(process)d:%(processName)s> %(name)s.%(funcName)s(): %(message)s"
        datefmt: '%Y-%m-%d:%H:%M:%S%z'

handlers:
    console:
        class: logging.StreamHandler
        level: NOTSET
        formatter: standard
        stream: ext://sys.stdout

    info_file_handler:
        # for file paths, make sure the directory location exists
        class: logging.handlers.TimedRotatingFileHandler
        level: INFO
        formatter: standard
        filename: demo.log
        when: midnight
        interval: 1
        backupCount: 0
        encoding: utf8

    debug_file_handler:
        class: logging.handlers.TimedRotatingFileHandler
        level: DEBUG
        formatter: error
        filename: demo_debug.log
        when: H
        interval: 6
        backupCount: 4
        encoding: utf8

    error_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: error
        filename: demo_error.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    critical_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: error
        filename: demo_critical.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

    warn_file_handler:
        class: logging.handlers.RotatingFileHandler
        level: WARNING
        formatter: error
        filename: demo_warning.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

root:
    level: NOTSET
    handlers: [console]
    propogate: no

loggers:
    demo:
        level: INFO
        handlers: [info_file_handler, error_file_handler, debug_file_handler]
        propogate: yes

    all:
        level: DEBUG
        handlers: [info_file_handler, error_file_handler, debug_file_handler, critical_file_handler, warn_file_handler]
        propogate: yes